## API Examples

### Example 1: RandomUser API

Bellow are Fet Methods parameters that we can generate. For more information on the parameters, please visit this s [documentation](https://randomuser.me/documentation) page.

### Get Methods

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the <code>randomuser</code> library running the <code>pip install</code> command.

In [8]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5093 sha256=6d83d5268c98c672e472ac62fe5414a4a57db3748cd1d16aa189c65f3e02fd77
  Stored in directory: c:\users\pauri\appdata\local\pip\cache\wheels\fc\8d\74\bcdd5e8a9433bfa4c4f9c1cccbfec40139322a28d77f61e45e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

Then we load the necessary libraries.

In [13]:
from randomuser import RandomUser
import pandas as pd

First we will create a random user object, r.

In [16]:
r = RandomUser()

Then, using <code>generate_users()</code> function, we get a list of random 10 users.

In [21]:
some_list = r.generate_users(10)

In [23]:
some_list

[<randomuser.RandomUser at 0x2be2af67110>,
 <randomuser.RandomUser at 0x2be2af67210>,
 <randomuser.RandomUser at 0x2be2af672d0>,
 <randomuser.RandomUser at 0x2be2af67290>,
 <randomuser.RandomUser at 0x2be2af67250>,
 <randomuser.RandomUser at 0x2be2af67190>,
 <randomuser.RandomUser at 0x2be2af67410>,
 <randomuser.RandomUser at 0x2be2af674d0>,
 <randomuser.RandomUser at 0x2be2af67390>,
 <randomuser.RandomUser at 0x2be2af67150>]

The <b>Get Methods</b> functions mentioned at the beginning os fhits notebook, can generate the required parametrs to construct a dataset. For example, to get a full name, we call <code>get_full_name()</code>function.

In [26]:
name = r.get_full_name()

Let's say we only need 10 users with full names and ther email address. We can rite a "for-loop" to print these 10 users.

In [29]:
for user in some_list:
    print(user.get_full_name()," ",user.get_email())

Angie Morrison   angie.morrison@example.com
Colin James   colin.james@example.com
Ernesto Medina   ernesto.medina@example.com
Maja Rasmussen   maja.rasmussen@example.com
Fiona Bowman   fiona.bowman@example.com
Randa Plasmeijer   randa.plasmeijer@example.com
Burçin Korteweg   burcin.korteweg@example.com
Jessica Anderson   jessica.anderson@example.com
Coşkun Karadaş   coskun.karadas@example.com
Tyler Roberts   tyler.roberts@example.com

### Exercise 1 

In this exercise, generate photos of the random 10 users.

In [34]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/men/68.jpg
https://randomuser.me/api/portraits/men/63.jpg
https://randomuser.me/api/portraits/women/89.jpg
https://randomuser.me/api/portraits/women/96.jpg
https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/women/38.jpg
https://randomuser.me/api/portraits/men/73.jpg
https://randomuser.me/api/portraits/men/68.jpg

To generate a table with information about the users, we can write a function containing all esirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [49]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [51]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Myrna Roode,female,Born,Drenthe,myrna.roode@example.com,1955-07-30T16:05:20.967Z,https://randomuser.me/api/portraits/women/20.jpg
1,Robyn Chiu,female,Hedel,Overijssel,robyn.chiu@example.com,1971-05-22T19:25:01.253Z,https://randomuser.me/api/portraits/women/30.jpg
2,آوا پارسا,female,کرمانشاه,تهران,aw.prs@example.com,1971-04-24T02:59:31.711Z,https://randomuser.me/api/portraits/women/8.jpg
3,Iiris Salonen,female,Jalasjärvi,Central Ostrobothnia,iiris.salonen@example.com,1980-04-22T06:02:12.909Z,https://randomuser.me/api/portraits/women/94.jpg
4,Alexis Roy,female,Sidney,Alberta,alexis.roy@example.com,1980-11-15T08:25:11.968Z,https://randomuser.me/api/portraits/women/6.jpg
5,Hardy Stürmer,male,Anklam,Rheinland-Pfalz,hardy.sturmer@example.com,1977-09-15T16:17:04.661Z,https://randomuser.me/api/portraits/men/34.jpg
6,Leah Cox,female,Cashel,Galway,leah.cox@example.com,1958-11-02T13:31:44.615Z,https://randomuser.me/api/portraits/women/92.jpg
7,Katerine Duarte,female,Alvorada,Santa Catarina,katerine.duarte@example.com,1949-04-26T19:53:39.133Z,https://randomuser.me/api/portraits/women/46.jpg
8,Emmi Düring,female,Friedrichstadt,Schleswig-Holstein,emmi.during@example.com,1988-09-20T08:12:05.943Z,https://randomuser.me/api/portraits/women/58.jpg
9,Elliot Bonnet,male,Champigny-sur-Marne,Seine-et-Marne,elliot.bonnet@example.com,1950-04-25T07:59:12.882Z,https://randomuser.me/api/portraits/men/10.jpg

In [57]:
df1 = pd.DataFrame(get_users())

Now we have a pandas dataframe that can be used for any testing purposes that testet might have.

### Example 2: Fruityvice API

Anothcer, more common woy to use APIs, is through <code>requests</code> library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [62]:
import requests 
import json

We will ontain the frutyvice API data <code>requests-get("url")</code> function. The data is in a json format.

In [65]:
data = requests.get("https://fruityvice.com/api/fruit/all")

We will retrieve results using <code>json.loads(/)</code> function

In [69]:
results = json.loads(data.text)

We will convert our json data into pandas data frame.

In [72]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The nutrition column contains multiple subcolumbns, so the data to be "flattened" or normalized.

In [75]:
df2 = pd.json_normalize(results)

In [77]:
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

Let's see if we can extract some informatiom from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [86]:
cherry = df2.loc[df2["name"]=="Cherry"]
cherry

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

### Exercise 2

In this Exercise, fin out how many calories are contained in a banana.

In [91]:
cal_banana = df2.loc[df2["name" ]=="Banana"]
cal_banana

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0

In [95]:
cal_banana.iloc[0][5]

C:\Users\pauri\AppData\Local\Temp\ipykernel_24256\3115526351.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cal_banana.iloc[0][5]

96

### Exercise 3

This page contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API

This API retturns random jokes from a database. The following URL can be used to retrive 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using <code>requests.get("url")</code> function, load the data from the URL

In [108]:
url = "https://official-joke-api.appspot.com/jokes/ten"

2. Retrive results using <code>json.loads()</code> function

In [119]:
data2= requests.get(url)
data2

3. Convert jso data into pandas data frame. Drop the type and id columns.

In [130]:
df3 = pd.DataFrame(results2)
df3

,type,setup,punchline,id
0,programming,A DHCP packet walks into a bar and asks for a ...,"Bartender says, ""here, but I’ll need that back...",368
1,general,Why did the invisible man turn down the job of...,He couldn't see himself doing it,51
2,general,Have you heard of the band 1023MB?,They haven't got a gig yet.,110
3,programming,Why did the programmer bring a broom to work?,To clean up all the bugs.,446
4,general,How do you get two whales in a car?,Start in England and drive West.,125
5,programming,How do you check if a webpage is HTML5?,Try it out on Internet Explorer,55
6,general,Do I enjoy making courthouse puns?,Guilty,105
7,general,Ever wondered why bees hum?,It's because they don't know the words.,108
8,general,Did you hear about the guy whose whole left si...,He's all right now.,89
9,general,Want to hear a chimney joke?,Got stacks of em! First one's on the house,150

In [132]:
df3.drop(columns=["type","id"],inplace=True)
df3

,setup,punchline
0,A DHCP packet walks into a bar and asks for a ...,"Bartender says, ""here, but I’ll need that back..."
1,Why did the invisible man turn down the job of...,He couldn't see himself doing it
2,Have you heard of the band 1023MB?,They haven't got a gig yet.
3,Why did the programmer bring a broom to work?,To clean up all the bugs.
4,How do you get two whales in a car?,Start in England and drive West.
5,How do you check if a webpage is HTML5?,Try it out on Internet Explorer
6,Do I enjoy making courthouse puns?,Guilty
7,Ever wondered why bees hum?,It's because they don't know the words.
8,Did you hear about the guy whose whole left si...,He's all right now.
9,Want to hear a chimney joke?,Got stacks of em! First one's on the house